---
title: "Check date in OBIS data"
author: "Yi-Ming Gan"
date: "`r Sys.Date()`"
output: github_document
---

Create a tibble of cut off date (end date) and a count of records with that end date.

```{r check record, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(httr)

# create tibble with end_date, 100 years interval
occ_df <- tibble(end_date = seq(ymd("0099-12-31"), ymd(today()), "100 years"))

# function to get occurrence record count per end_date
get_occ_count_with_end_date <- function(end_date){
  url <- "https://api.obis.org/"
  r = GET(url, path = "v3/occurrence", query = list(enddate = end_date))
  count <- content(r)$total  # get the count of records from query content
  return(count)
}

# create columns of record count for the end_date and earliest valid date
occ_df <- occ_df %>%
  rowwise() %>%
  mutate(
    count = get_occ_count_with_end_date(end_date),
    earliest_valid_date = end_date + days(1))

occ_df
```

## Occurrences with end date prior 1700

The number of dates with 0001 seems unusual ... Let's see what are the dates.

```{r unique years, warning=FALSE, message=FALSE}
library(robis)

end_date <- ymd("1699-12-31")
max_end_date <- year(end_date + years(1))  # 1700, for x-axis

# get all occurrence with enddate = end_date
occ <- occurrence(enddate = end_date)

# list all eventDate prior end_date
sort(occ$eventDate)

# plot histogram of the year
ggplot(occ, aes(date_year)) + 
  geom_histogram(bins=100) +
  scale_x_continuous(breaks = seq(0, max_end_date, 100))

```

Out of curiosity, check which datasets have those `date_year`

```{r old datasets, warning=FALSE, message=FALSE}
occ %>% 
  count(date_year, dataset_id) %>%
  rowwise() %>%
  mutate(datasetName = dataset(datasetid = dataset_id)$title)
```

